language: php

sudo: false

cache:
  directories:
        - $HOME/.composer/cache

php:
  - 5.6

before_script:
  - mysql -e 'create database homestead_test;'
  - composer install
  - php artisan migrate:install
  - php artisan migrate:refresh --seed

script: phpunit

notifications:
    on_success: never
    on_failure: always