version: "3"
services:

  nginx-proxy:
    image: jwilder/nginx-proxy:alpine
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    labels:
          com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    volumes:
      - ./nginx-proxy/data/htpasswd:/etc/nginx/htpasswd:ro
      - ./nginx-proxy/data/certs:/etc/nginx/certs:ro
      - ./nginx-proxy/data/vhost.d:/etc/nginx/vhost.d
      - ./nginx-proxy/data/conf.d:/etc/nginx/conf.d
      - nginx-proxy-html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - nginx

  letsencrypt-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt-companion
    restart: always
    volumes:
      - ./nginx-proxy/data/certs:/etc/nginx/certs:rw
      - ./nginx-proxy/data/vhost.d:/etc/nginx/vhost.d:rw
      -  nginx-proxy-html:/usr/share/nginx/html:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - nginx-proxy

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    volumes:
      - ../:/var/www/html
    environment:
      VIRTUAL_HOST: mygrades.de,www.mygrades.de
      LETSENCRYPT_HOST: mygrades.de,www.mygrades.de
      LETSENCRYPT_EMAIL: hallo@mygrades.de
      VIRTUAL_PORT: 8080
    depends_on:
      - php
    expose:
      - 8080
    user: "${USER_ID}"

  php:
    build: ./php
    container_name: php
    restart: always
    volumes:
      - ../:/var/www/html
    depends_on:
      - db
    user: "${USER_ID}"

  db:
    image: mysql:5.7
    container_name: db
    restart: always
    volumes:
      - db-data:/var/lib/mysql
      - ./db:/run/secrets
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE_FILE: /run/secrets/database
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/root-password
      MYSQL_USER_FILE: /run/secrets/user
      MYSQL_PASSWORD_FILE: /run/secrets/password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      VIRTUAL_HOST: pma.mygrades.de,www.pma.mygrades.de
      LETSENCRYPT_HOST: pma.mygrades.de,www.pma.mygrades.de
      LETSENCRYPT_EMAIL: hallo@mygrades.de
      PMA_HOST: db
      PMA_PORT: 3306
    depends_on:
      - db

volumes:
  db-data:
  nginx-proxy-html:
